# Generated by Django 2.1.4 on 2018-12-04 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_customerbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TOP_UP', 'top_up'), ('WITHDRAW', 'withdraw'), ('TRANSFER', 'transfer')], max_length=150)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure'), ('PENDING', 'pending')], max_length=150)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('performed_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_transactions', to='accounts.CustomerBankAccount')),
            ],
        ),
    ]
